/*PROCEDURES*/
USE EMPRESA
GO

CREATE TABLE PESSOA(
	IDPESSOA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL CHECK(SEXO IN('M','F')),
	NASCIMENTO DATE NOT NULL
)
GO


CREATE TABLE TELEFONE_PROD(
	IDTELEFONE INT NOT NULL IDENTITY,
	TIPO CHAR(3) NOT NULL CHECK(TIPO IN('CEL','COM')),
	NUMERO CHAR(10) NOT NULL,
	ID_PESSOA INT
)
GO

ALTER TABLE TELEFONE_PROD ADD CONSTRAINT FK_TELEFONE_PESSOA
FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(IDPESSOA)
ON DELETE CASCADE
GO

INSERT INTO PESSOA VALUES('ANTONIO','M','1981-02-13')
INSERT INTO PESSOA VALUES('DANIEL','M','1985-03-18')
INSERT INTO PESSOA VALUES('CLEIDE','F','1991-10-29')
INSERT INTO PESSOA VALUES('MARCIA','F','1999-09-26')

SELECT @@IDENTITY -- GUARDA O ULTIMO IDENTITY INSERIDO NA SEÇÃO
GO

INSERT INTO TELEFONE_PROD VALUES('CEL','98790089',1)
INSERT INTO TELEFONE_PROD VALUES('COM','85570996',1)
INSERT INTO TELEFONE_PROD VALUES('CEL','89556723',2)
INSERT INTO TELEFONE_PROD VALUES('COM','85223379',2)
INSERT INTO TELEFONE_PROD VALUES('CEL','95356689',3)
INSERT INTO TELEFONE_PROD VALUES('CEL','88556896',4)

SELECT * FROM PESSOA
SELECT * FROM TELEFONE
GO

/*CRIANDO A PROCEDURE*/
CREATE PROC SOMA
AS SELECT 10 + 10 AS SOMA
GO
/*EXECUÇÃO DA PROCEDURE*/
SOMA
--OU
EXEC SOMA
GO
/*DINAMICAS - COM PARAMETROS*/
CREATE PROC CONT @NUM1 INT, @NUM2 INT
AS
	SELECT @NUM1 + @NUM2 AS RESULTADO
GO
/*EXECUTANDO*/
EXEC CONT 90, 78
GO
/*APAGANDO A PROCEDURE*/
DROP PROC CONT
GO
/*PROCEDURES EM TABELAS*/
SELECT NOME, NUMERO
FROM PESSOA
INNER JOIN TELEFONE_PROD
ON IDPESSOA = ID_PESSOA
WHERE TIPO = 'CEL'
GO

/*TRAZER OS TELEFONES DE ACORDO COM O TIPO PASSADO*/
CREATE PROC TELEFONES @TIPO CHAR(3)
AS
	SELECT NOME, NUMERO
	FROM PESSOA
	INNER JOIN TELEFONE_PROD
	ON IDPESSOA = ID_PESSOA
	WHERE TIPO = @TIPO
GO
EXEC TELEFONES 'CEL'
GO
EXEC TELEFONES 'COM'
GO
/*PARAMETROS DE OUTPUT*/
SELECT TIPO, COUNT(*) AS QUANTIDADE
FROM TELEFONE_PROD
GROUP BY TIPO
GO

CREATE PROC GETTIPO @TIPO CHAR(3), @CONTADOR INT OUTPUT
AS
	SELECT @CONTADOR  = COUNT(*)
	FROM TELEFONE_PROD
	WHERE TIPO = @TIPO
GO

/*EXECUÇÃO DA PROC COM PARAMETRO DE SAIDA*/
DECLARE @SAIDA INT
EXEC GETTIPO @TIPO = 'CEL', @CONTADOR = @SAIDA OUTPUT
SELECT @SAIDA
GO

DECLARE @SAIDA INT
EXEC GETTIPO 'CEL', @SAIDA OUTPUT
SELECT @SAIDA
GO

/*PROCEDURE DE CADASTRO*/
CREATE PROC CADASTRO @NOME VARCHAR(30), @SEXO CHAR(1), @NASCIMENTO DATE,
@TIPO CHAR(3), @NUMERO VARCHAR(10)
AS
 DECLARE @FK INT
 INSERT INTO PESSOA VALUES(@NOME, @SEXO, @NASCIMENTO) -- GERAR UM ID
 SET @FK = (SELECT IDPESSOA FROM PESSOA WHERE IDPESSOA = @@IDENTITY)
 INSERT INTO TELEFONE_PROD VALUES (@TIPO, @NUMERO, @FK)
GO

CADASTRO 'JORGE','M','1981-01-02','CEL','97273822'
GO

SELECT PESSOA.*, TELEFONE_PROD.*
FROM PESSOA
INNER JOIN TELEFONE_PROD
ON IDPESSOA = ID_PESSOA
GO
